export const PROJECTS = [
    {
      id: 'jinro',
      kicker: 'React Full-cycle · ShopBy API',
      title: '진로토닉몰',
      desc: 'ShopBy API 기반 React 쇼핑몰 · 설계·개발·배포 80% 단독 수행',
      gradient: 'linear-gradient(140deg, #0A50EA, #6366F1)',
      badge: 'React Full-cycle',
      num: '01',
      metrics: [
        { val: '80%', lbl: '단독 개발' },
        { val: '6M',  lbl: '설계 → 배포' },
        { val: '20+', lbl: '컴포넌트'  },
      ],
      tags: ['React', 'ShopBy API', 'SCSS', 'Vite'],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: 'ShopBy 플랫폼 기반 신규 쇼핑몰 구축. 외부 API 스펙을 처음부터 직접 파악해야 하는 상황',
        t: '역할(TASK) : 컴포넌트 설계, React 개발, API 연동, 배포까지 전 과정을 주도.',
        a: 'ShopBy API 문서를 분석하고 메인 · 상품 상세 · 장바구니 · 주문 · 마이페이지를 단위별 재사용 컴포넌트로 설계해 구현',
        r: '일정 내 런칭 완료. 재사용 컴포넌트 구조로 이후 유지보수 공수를 대폭 절감',
      },
      troubleshooting: [
        {
          tag: '로직',
          q: '복합 쿠폰 적용 로직 처리 및 조건 분기 최적화 이슈',
          p: '[문제점] 주문 페이지에서 상품 쿠폰과 장바구니 쿠폰의 적용 조건이 상이하고, 특정 상품에 쿠폰이 적용 불가능할 경우 전체 쿠폰 적용 흐름에 영향을 주는 복잡한 로직이 존재함. 특히 상품 쿠폰은 개별 적용, 장바구니 쿠폰은 전체 적용 방식이 혼합되어 있어 예외 처리 및 충돌이 빈번히 발생함.',
          s: '[해결] 쿠폰 적용 대상(상품/장바구니)을 기준으로 쿠폰 데이터를 분리하고, 상품별 조건/쿠폰불가 플래그 등을 기준으로 사전에 필터링하는 로직을 추가하여 적용 가능한 쿠폰만 사용자에게 표시되도록 개선함.',
          r: '[회고] 조건 분기 로직은 한눈에 보이도록 설계하고, 유스케이스별 테스트 케이스 작성 필요성을 느낌',
        },
        {
          tag: '성능',
          q: '장바구니 수량 변경 시 UI는 반영되지만 서버에는 반영되지 않는 현상',
          p: '[문제점] 장바구니에서 수량을 변경했을 때 UI에서는 정상적으로 수량이 바뀌었지만, 서버 요청에는 변경된 수량이 반영되지 않아 DB에 저장되지 않는 문제 발생',
          d: '[디버깅] console.log를 활용해 변경된 수량 상태(state)와 실제 API 요청 시점의 데이터를 비교하면서 확인한 결과, 상태가 아직 업데이트되기 전의 값이 API에 전달되고 있었음',
          s: '[해결] setState가 비동기적으로 처리된다는 점을 인지하고, useEffect 또는 이벤트 핸들러 내부에서 최신 상태를 보장하도록 구조 수정',
          r: '[회고] 상태 변화 이후 바로 API 호출이 필요한 경우, useEffect 또는 상태 콜백을 통해 시점을 명확히 분리해야 함을 체감',
        },
      ],
      links: {
        live:   'https://www.jinrotonic.com/',
      },
    },
    {
      id: 'hddf',
      kicker: '대형 이커머스 고도화 · 퍼블리싱 품질 관리',
      title: '현대면세점',
      desc: '대형 이커머스 고도화  · 이벤트 페이지 정기 제작  · 퍼블리싱 품질관리 ',
      gradient: 'linear-gradient(140deg, #7C3AED, #A855F7)',
      badge: '이커머스 고도화',
      num: '02',
      metrics: [
        { val: '대형', lbl: '브랜드 규모' },
        { val: '30%', lbl: '일정 단축'  },
        { val: '50+',  lbl: '이벤트' },
        { val: '4+', lbl: '명품관 리뉴얼'},
      ],
      tags: ['javescript', 'CSS', 'Axios', 'Bitbuket', 'Bamboo'],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: '로그인 이탈률이 높고, 브랜드관 구매전환율 개선이 필요한 상황. 이벤트 페이지는 작업자마다 코드 스타일이 달라 유지보수 비용 높음.',
        t: '고객 경험 개선, 구매전환율 향상, 팀 생산성 확보 세 가지를 동시에 목표',
        a: '로그인 페이지는 고객 행동 데이터 기반으로 구조를 재설계하고 접근성을 개선. 브랜드관은 세일/신상품/베스트 영역과 필터를 신규 개발. 이벤트 템플릿은 모듈화 후 스니펫으로 제작해 팀 공유.',
        r: '로그인 작업 일정 30% 단축(10일 → 7일), 구매전환율 +0.7%p 향상, 정기 이벤트 작업 시간 2시간 단축 달성',
      },
      troubleshooting: [
        {
          tag: 'GA4 ',
          q: 'GA4 이벤트 태깅 적용',
          r: '주요 UI요소에 GA4 이벤트 태깅을 적용하고, 옴니버그(Omnibug)를 통해 정상 수집 여부를 확인',
        },
      ],
      links: {
        live:   'https://www.hddfs.com/shop/dm/main.do',
      },
    },
    {
      id: 'ns',
      kicker: 'CAFE24 쇼핑몰 운영 · 게임형 이벤트 제작 · React 백오피스 개발',
      title: '농심몰',
      desc: 'Cafe24 운영 · 게임형 이벤트 10+ · React 백오피스 직접 설계',
      gradient: 'linear-gradient(140deg, #DD1E25, #EC4899)',
      badge: 'Cafe24 운영 · BO 개발',
      num: '03',
      metrics: [
        { val: '10+', lbl: '게임형 이벤트' },
        { val: 'BO',  lbl: '설계' },
        { val: '↓30%', lbl: '운영 공수'  },
      ],
      tags: ['React', 'Axios', 'CAFE24API', 'Javasciprt', 'SCSS', 'Vite'],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: 'Cafe24 기반 쇼핑몰 운영 중 신규 "ㅋㅋㅋTV" 페이지와 백오피스 개발이 동시에 필요한 상황',
        t: '게임형 이벤트 월 1회 정기 제작, "ㅋㅋㅋTV" 페이지 구축, React 백오피스 설계 및 API 연동을 담당',
        a: 'CSS/JS 애니메이션 기반 게임 이벤트를 구현하고, React로 BO를 직접 설계해 Cafe24 API와 연동, 콘텐츠 데이터 관리를 자동화',
        r: '운영 공수 약 30% 절감. 비개발 팀도 직접 운영 가능한 구조 완성',
      },
      troubleshooting: [
        {
          tag: 'URL',
          q: 'ㅋㅋㅋTV URL 설계 및 보안 넘버 가독성 이슈로 인하여 URL 구조를 직접 설계',
          p: '[문제점] 백엔드에서 제공한 카테고리 식별값이 보안상 영문/숫자 혼합 형태여서 클라이언트 요청과 달리 직관적인 URL 구조 제공이 어려움',
          s: '[해결] 프론트에서 한글 카테고리명을 slug 형태로 변환하고, 해당 값을 라우터 경로에 매핑하여 사용자 친화적 URL 구현',
          r: '[회고] 보안과 사용성 사이에서 균형 잡힌 접근이 필요하며, 프론트에서 URL 구조를 전략적으로 설계해야 함을 경험함',
        },
        {
          tag: '무한',
          q: 'ㅋㅋㅋTV 리스트 페이지 구축 및 무한 스크롤 구현',
          p: '[문제점] 리스트 영역은 무한 스크롤 방식으로 구현하여 15개 단위로 콘텐츠 로딩',
          s: '[해결] 로딩 시 Skeleton UI 적용으로 사용자 경험 강화',
        },
      ],
      links: {
        live:   'https://www.nongshimmall.com',
      },
    },
    {
      id: 'dr',
      kicker: 'CAFE24 쇼핑몰 구축 · React 백오피스 개발',
      title: '닥터포헤어',
      desc: 'Cafe24 쇼핑몰 구축 및 BO 직접 설계 후 연동',
      gradient: 'linear-gradient(140deg, #EA580C, #F59E0B)',
      badge: 'Cafe24 구축 · BO 개발',
      num: '04',
      metrics: [
        // { val: '10+', lbl: '게임형 이벤트' },
        // { val: 'BO',  lbl: '설계' },
        // { val: '↓30%', lbl: '운영 공수'  },
      ],
      tags: ['React', 'Axios', 'CAFE24', 'Javasciprt', 'SCSS', 'Vite'],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: 'Cafe24 기반 쇼핑몰 운영 중 신규 "ㅋㅋㅋTV" 페이지와 백오피스 개발이 동시에 필요한 상황',
        t: '게임형 이벤트 월 1회 정기 제작, "ㅋㅋㅋTV" 페이지 구축, React 백오피스 설계 및 API 연동을 담당',
        a: 'CSS/JS 애니메이션 기반 게임 이벤트를 구현하고, React로 BO를 직접 설계해 Cafe24 API와 연동, 콘텐츠 데이터 관리를 자동화',
        r: '운영 공수 약 30% 절감. 비개발 팀도 직접 운영 가능한 구조 완성',
      },
      troubleshooting: [
        {
          tag: '이미지',
          q: '이미지 업로드 방식 결정 과정에서의 연동 및 기획 이슈',
          p: '[문제점] 초기에는 파일 용량과 안정성 등을 고려해 FormData 방식으로 구현을 계획했으나, 프론트 구현과 디버깅 과정에서 복잡도가 높아졌고, 백엔드 연동 시 포맷 오류가 반복 발생',
          s: '[해결] 기획팀과 협의하여 이미지가 저용량 1건 제한이라는 점을 고려해 base64 방식으로 전환, 백엔드와 포맷 합의 후 안정적으로 업로드 처리 완료',
          r: '[회고] 기술 선택은 상황에 따라 유연하게 접근해야 하며, 기획/백엔드와의 소통을 통해 목적에 맞는 최적의 방식으로 조정하는 것이 중요함을 경험함',
        },
        {
          tag: 'UI',
          q: '디자인 시안과 플랫폼 구조 간 불일치로 인한 퍼블리싱 충돌 이슈',
          p: '[문제점] Figma 디자인 시안과 카페24 기본 구조(템플릿/모듈)의 마크업 구조가 상이하여 퍼블리싱 요소가 깨지는 문제 발생',
          s: '[해결] 예전 카페24 모듈을 참고하여 만든 디자인 시안임을 파악한 뒤, 디자인팀에게 플랫폼의 고정 레이아웃의 구조 전달하여 디자인 재요청하여 최대한 시안과 유사하게 구현',
          r: '[회고] CMS 기반 플랫폼 개발에서는 디자인 재현도와 플랫폼 제약 사이에서 균형을 맞추는 UI 전략이 필요하다는 것을 체감함',
        },
      ],
      links: {
        live:   'https://www.drforhair.co.kr/',
      },
    },
    {
      id: 'ac',
      kicker: 'CAFE24 쇼핑몰 운영',
      title: '아윤채몰',
      desc: '주요 화면(UI)의 개선 및 유지보수 작업',
      gradient: 'linear-gradient(140deg, #059669, #14B8A6)',
      badge: 'CAFE24 쇼핑몰 운영',
      num: '05',
      metrics: [
        // { val: '10+', lbl: '게임형 이벤트' },
        // { val: 'BO',  lbl: '설계' },
        // { val: '↓30%', lbl: '운영 공수'  },
      ],
      tags: ['CAFE24', 'Javasciprt', 'SCSS', 'JavaScript'],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: '상품 상세페이지 이미지 교체 및 콘텐츠 수정',
        t: '신규 프로모션 및 시즌별 제품에 맞춰 상세페이지 이미지 교체',
        a: '카페24 관리 페이지 및 사용자 UI 유지보수',
      },
      troubleshooting: [
        
      ],
      links: {
        live:   'https://ayunche.com/index.html',
      },
    },
    {
      id: 'fd',
      kicker: 'CAFE24 쇼핑몰 운영',
      title: '후디스몰',
      desc: '주요 화면(UI)의 개선 및 유지보수 작업',
      gradient: 'linear-gradient(140deg, #334155, #64748B)',
      badge: 'CAFE24 쇼핑몰 운영',
      num: '06',
      metrics: [
        // { val: '10+', lbl: '게임형 이벤트' },
        // { val: 'BO',  lbl: '설계' },
        // { val: '↓30%', lbl: '운영 공수'  },
      ],
      tags: ['CAFE24', 'Javasciprt', 'SCSS', 'JavaScript'],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: 'UI 개선 및 유지보수 퍼블리싱',
        t: '후디스몰의 베스트 상품 페이지, 브랜드관, 헤더 등 주요 화면의 UI 개선 퍼블리싱 작업',
        a: '디자인팀에서 제공한 Figma 시안 기반으로 마크업 구조 개선 및 스타일링 작업 수행',
        r: '시즌별 프로모션에 맞춰 배너 디자인 교체 및 반응형 대응 퍼블리싱 반복 수행',
      },
      troubleshooting: [
        
      ],
      links: {
        live:   'https://foodismall.com/',
      },
    },
  ]