export const PROJECTS = [
    {
      id: 'jinro',
      kicker: 'React Full-cycle · ShopBy API',
      title: '진로토닉몰',
      desc: 'ShopBy 헤드리스 API 기반 React 쇼핑몰 · 컴포넌트 설계·개발·배포 80% 단독 수행',
      gradient: 'linear-gradient(140deg, #0A50EA, #6366F1)',
      badge: 'React Full-cycle',
      num: '01',
      metrics: [
        { val: '80%', lbl: '단독 개발' },
        { val: '6M',  lbl: '설계 → 배포' },
        { val: '20+', lbl: '컴포넌트'  },
      ],
      tags: ['React', 'ShopBy API', 'SCSS'],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: 'ShopBy 플랫폼 기반 신규 쇼핑몰 구축으로 외부 API 스펙을 처음부터 직접 파악해야 하는 상황',
        t: '컴포넌트 설계, React 개발, API 연동, 배포까지 전 과정을 주도',
        a: '외부 API 문서를 직접 분석해 메인 · 상품상세 · 장바구니 · 마이페이지 등 재사용 가능한 컴포넌트 단위로 설계',
        r: '일정 내 런칭 완료. 재사용 컴포넌트 구조로 이후 유지보수 공수 절감',
      },
      troubleshooting: [
        {
          tag: '로직',
          q: '복합 쿠폰 조건 분기 이슈',
          p: '[문제] 상품·장바구니 쿠폰의 적용 조건이 달라 쿠폰 불가 상품 포함 시 전체 흐름에 충돌 발생',
          d: '[디버깅] 쿠폰 적용 시점 데이터를 console.log로 확인 → 불가 상품에도 쿠폰이 노출되는 구조 파악',
          s: '[해결] 쿠폰 대상 기준으로 데이터 분리 후 불가 플래그로 사전 필터링해 유효 쿠폰만 노출',
          r: '[회고] 조건 분기가 복잡할수록 유스케이스별 테스트 케이스 정리가 필요함을 체감',
        },
        {
          tag: '비동기',
          q: '수량 변경 시 서버에 이전 값이 전달되는 문제',
          p: '[문제] 장바구니 수량 변경 시 UI는 반영되나 서버엔 변경 전 값이 전달됨',
          d: '[디버깅] console.log로 state와 API 요청 시점 데이터 비교 → setState 완료 전 API가 호출되는 것 확인',
          s: '[해결] useEffect로 API 호출 시점을 상태 업데이트 이후로 분리해 해결',
          r: '[회고] 상태 변경 직후 API 호출이 필요한 경우 useEffect로 시점을 명확히 분리해야 함을 체감',
        },
      ],
      links: {
        live:   'https://www.jinrotonic.com/',
      },
    },
    {
      id: 'hddf',
      kicker: 'E-commerce UX & Publishing',
      title: '현대면세점',
      desc: '주요 서비스 리뉴얼 · 운영 퍼블리싱 · 공통 템플릿 구축',
      gradient: 'linear-gradient(140deg, #7C3AED, #A855F7)',
      badge: '대형 이커머스 고도화',
      num: '02',
      metrics: [
        { val: '8+', lbl: '리뉴얼 프로젝트'},
        { val: '40+',  lbl: '이벤트 페이지' },
        { val: '30%', lbl: '일정 단축'  },
      ],
      tags: ['JavaScript','CSS','GA4'],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: '주요 서비스 리뉴얼을 단독으로 담당하는 동시에, 이벤트 페이지마다 다른 코드 스타일로 인해 유지보수가 어려운 상황',
        t: '퍼블리싱 품질을 유지하며, 반복 작업을 줄이고 운영 효율을 높일 수 있는 구조 구축',
        a: '명품관·브랜드관·로그인·웰니스관 리뉴얼을 단독 수행. GA4 이벤트 태깅과 Omnibug 검증으로 데이터 정확성을 확보. 이벤트 페이지를 공통 템플릿과 스니펫으로 팀에 공유.',
        r: '리뉴얼을 일정 내 완수. 이벤트 제작 속도와 코드 일관성을 높여 유지보수 및 협업 효율을 개선',
      },
      troubleshooting: [
      ],
      links: {
        live:   'https://www.hddfs.com/shop/dm/main.do',
      },
    },
    {
      id: 'ns',
      kicker: 'Cafe24 쇼핑몰 운영 · 게임형 이벤트 제작 · React 백오피스 개발',
      title: '농심몰',
      desc: '게임형 이벤트 제작부터 React 기반 운영 도구 개발까지 담당',
      gradient: 'linear-gradient(140deg, #DD1E25, #EC4899)',
      badge: '운영 고도화 · React BO 개발',
      num: '03',
      metrics: [
        { val: '30%', lbl: '운영 공수 절감' },
        { val: '10+', lbl: '게임형 이벤트' },
        { val: '1',  lbl: 'React BO 구축' },
      ],
      tags: ['React','Axios', 'SCSS','Cafe24',],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: 'Cafe24 기반 쇼핑몰 운영 중 신규 "ㅋㅋㅋTV" 페이지와 백오피스 개발이 동시에 필요한 상황',
        t: '게임형 이벤트 월 1회 정기 제작, "ㅋㅋㅋTV" 페이지 구축, React 백오피스 설계 및 API 연동을 담당',
        a: 'CSS·JavaScript 기반 게임형 이벤트를 구현하고, React로 백오피스를 직접 설계해 Cafe24 API와 연동하여 콘텐츠 등록 및 관리 기능을 구현',
        r: '운영 공수 약 30% 절감. 비개발 팀도 콘텐츠를 직접 관리할 수 있는 운영 환경을 구축',
      },
      troubleshooting: [
        {
          tag: 'Routing',
          q: '보안 식별값을 그대로 노출하지 않으면서도 사용자가 이해하기 쉬운 URL 구조',
          p: '[문제점] 백엔드에서 제공한 카테고리 식별값이 보안상 영문/숫자 혼합 형태여서 클라이언트 요청과 달리 직관적인 URL 구조 제공이 어려움',
          s: '[해결] 프론트에서 한글 카테고리명을 slug 형태로 변환하고, 해당 값을 라우터 경로에 매핑하여 사용자 친화적 URL 구현',
          r: '[회고] 보안과 사용성 사이에서 균형 잡힌 접근이 필요하며, 프론트에서 URL 구조를 전략적으로 설계해야 함을 경험함',
        },
        {
          tag: 'Infinite Scroll',
          q: 'ㅋㅋㅋTV 리스트 페이지의 무한 스크롤 구현',
          p: '[문제점] 추가 데이터를 불러오는 동안 화면이 비어 보이면서 사용자가 로딩 상태를 인지하기 어려운 상태',
          s: '[해결] Skeleton UI를 적용해 로딩 상태를 시각적으로 표현하고, 콘텐츠가 자연스럽게 이어지도록 구현',
          r: '[결과] 콘텐츠 로딩 과정의 이질감을 줄여 보다 자연스러운 탐색 경험을 제공',
        },
      ],
      links: {
        live:   'https://www.nongshimmall.com',
      },
    },
    {
      id: 'dr',
      kicker: 'Cafe24 쇼핑몰 구축 · React 백오피스 개발',
      title: '닥터포헤어',
      desc: '쇼핑몰 구축부터 React 기반 운영 도구 개발까지 담당',
      gradient: 'linear-gradient(140deg, #EA580C, #F59E0B)',
      badge: '신규 구축 · React BO 개발',
      num: '04',
      metrics: [
        { val: '50%', lbl: '구축 참여' },
        { val: 'BO',  lbl: '직접 설계' },
        { val: 'API', lbl: '연동 구현'  },
      ],
      tags: ['React', 'Axios', 'SCSS', 'Cafe24'],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: '신규 Cafe24 쇼핑몰 구축과 운영을 위한 React 백오피스 개발이 동시에 필요한 프로젝트',
        t: '쇼핑몰과 백오피스를 안정적으로 구축하고 API 기반 운영 환경 구현',
        a: '쇼핑몰 퍼블리싱을 진행하는 동시에 React 기반 백오피스를 직접 설계했습니다. API 연동을 통해 콘텐츠 등록·수정 기능을 구현하고 쇼핑몰과 데이터를 연계하는 운영 구조를 구축했습니다.',
        r: '신규 쇼핑몰과 백오피스를 모두 성공적으로 구축했으며, 운영자가 직접 관리 가능한 운영 환경을 완성',
      },
      troubleshooting: [
        {
          tag: 'Image Upload',
          q: '이미지 업로드 방식 결정 과정에서의 연동 및 기획 이슈',
          p: '[문제점] 초기에는 파일 용량과 안정성 등을 고려해 FormData 방식으로 구현을 계획했으나, 프론트 구현과 디버깅 과정에서 복잡도가 높아졌고, 백엔드 연동 시 포맷 오류가 반복 발생',
          s: '[해결] 기획팀과 협의하여 이미지가 저용량 1건 제한이라는 점을 고려해 base64 방식으로 전환, 백엔드와 포맷 합의 후 안정적으로 업로드 처리 완료',
          r: '[회고] 기술 선택은 상황에 따라 유연하게 접근해야 하며, 기획/백엔드와의 소통을 통해 목적에 맞는 최적의 방식으로 조정하는 것이 중요함을 경험함',
        },
        {
          tag: 'Cafe24 UI',
          q: '디자인 시안과 플랫폼 구조 불일치',
          p: '[문제점] Figma 시안과 Cafe24 기본 모듈 구조가 달라 UI 구현 충돌 발생',
          s: '[해결] 플랫폼 제약사항을 디자인팀과 공유하고 구조에 맞게 시안을 조정하여 퍼블리싱 진행',
          r: '[결과] 플랫폼 구조를 유지하면서 디자인 의도를 최대한 반영한 UI 구현',
        },
      ],
      links: {
        live:   'https://www.drforhair.co.kr/',
      },
    },
    {
      id: 'ac',
      kicker: 'Cafe24 쇼핑몰 운영',
      title: '아윤채몰',
      desc: '프로모션에 따른 UI·콘텐츠 유지보수 및 Cafe24 쇼핑몰 운영',
      gradient: 'linear-gradient(140deg, #059669, #14B8A6)',
      badge: 'Cafe24 쇼핑몰 운영',
      num: '05',
      metrics: [
      ],
      tags: ['Axios', 'JavaScript', 'CSS','Cafe24',],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: '프로모션 및 시즌별 콘텐츠 변경이 빈번한 Cafe24 쇼핑몰 운영',
        t: '운영 일정에 맞춘 UI 및 콘텐츠 안정적 반영',
        a: '상품 상세페이지, 메인 화면, 프로모션 영역의 UI 및 콘텐츠를 수정하고 Cafe24 관리자 기능을 활용해 운영 지원',
        r: '운영 일정에 맞춰 콘텐츠를 안정적으로 반영하고 쇼핑몰 품질 유지',
      },
      troubleshooting: [
        
      ],
      links: {
        live:   'https://ayunche.com/index.html',
      },
    },
    {
      id: 'fd',
      kicker: 'UI 개선 · Cafe24 쇼핑몰 운영',
      title: '후디스몰',
      desc: '주요 화면 리뉴얼 및 Cafe24 쇼핑몰 운영',
      gradient: 'linear-gradient(140deg, #334155, #64748B)',
      badge: 'Cafe24 쇼핑몰 운영',
      num: '06',
      metrics: [
      ],
      tags: ['Cafe24', 'JavaScript', 'CSS'],
      screenshots: [
        { src: '/images/projects/jinro/main.png',   label: '메인 · 상품 화면'  },
        { src: '/images/projects/jinro/cart.png',   label: '장바구니 · 주문'   },
        { src: '/images/projects/jinro/mypage.png', label: '마이페이지'        },
        { src: '/images/projects/jinro/mobile.png', label: '모바일 반응형'     },
      ],
      star: {
        s: 'Cafe24 기반 쇼핑몰의 주요 화면 개선 및 운영 퍼블리싱 필요',
        t: '사용성과 디자인 일관성을 고려한 UI 개선 및 프로모션 반영',
        a: '베스트 상품, 브랜드관, 헤더 등 주요 화면 퍼블리싱, Figma 시안 기반 마크업 및 스타일 개선, 반응형 UI 적용',
        r: '프로모션 일정에 맞춘 안정적인 운영 지원 및 사용자 경험 향상',
      },
      troubleshooting: [
      ],
      links: {
        live:   'https://foodismall.com/',
      },
    },
  ]